------------------------------------------------------------------------------
CREATE TABLE  ENUM_EVENT_PRIORITY  --Success,Primary,Info,Danger,Dark...
(
	ID 				SERIAL NOT NULL,
	ORDER_CODE		VARCHAR(50),

	SHORT_NAME		VARCHAR(20) NOT NULL,
	FULL_NAME		VARCHAR(20) NOT NULL,
	
	STATE_ID		INT NOT NULL,	
	CREATED_AT		TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	
	CONSTRAINT FK_STATE_ID
		FOREIGN KEY (STATE_ID)
			REFERENCES ENUM_STATE (ID)
);

CREATE TABLE ENUM_EVENT_PRIORITY_TRANSLATE
(
	ID			 	SERIAl NOT NULL PRIMARY KEY,
	OWNER_ID	 	INT NOT NULL,
	LANGUAGE_ID	 	INT NOT NULL,
	COLUMN_NAME  	VARCHAR(100) NOT NULL,
	TRANSLATE_TEXT	TEXT NOT NULL,

	CREATED_AT		TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	
	CONSTRAINT FK_OWNER_ID
		FOREIGN KEY (OWNER_ID) 
			REFERENCES ENUM_EVENT_PRIORITY (ID)
				ON DELETE CASCADE,
	CONSTRAINT FK_LANGUAGE_ID 
		FOREIGN KEY (LANGUAGE_ID)
			REFERENCES ENUM_LANGUAGE (ID)
);

INSERT INTO ENUM_EVENT_PRIORITY(ID,ORDER_CODE,SHORT_NAME,FULL_NAME,STATE_ID)
VALUES
	(1,'001',N'Success',N'Success',1),
	(2,'002',N'Danger',N'Danger',1),
	(3,'003',N'Primary',N'Primary',1),
	(4,'004',N'Info',N'Info',1),
	(4,'005',N'Warning',N'Warning',1);

------------------------------------------------------------------------------
CREATE TABLE ENUM_EVENT_TYPE 	-- Bemor ko'rigi, Ishga taluqli boshqa event , Shaxsiy event
(
    ID 				INT NOT NULL PRIMARY KEY,
    ORDER_CODE 		VARCHAR(50),
    SHORT_NAME 		VARCHAR(250) not null,
    FULL_NAME  		VARCHAR(300) not null,
	STATE_ID		INT NOT NULL,
	
    CREATED_AT 		TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
	
	CONSTRAINT FK_STATE_ID
		FOREIGN KEY (STATE_ID)
			REFERENCES ENUM_STATE (ID)
);

CREATE TABLE ENUM_EVENT_TYPE_TRANSLATE
(
	ID 				SERIAL NOT NULL PRIMARY KEY,
	OWNER_ID		INT NOT NULL,
	LANGUAGE_ID 	INT NOT NULL,
	COLUMN_NAME		VARCHAR(100) NOT NULL,
	TRANSLATE_TEXT  TEXT NOT NULL,
	CREATED_AT  	TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
	
	CONSTRAINT FK_OWNER_ID
		FOREIGN KEY (OWNER_ID) 
			REFERENCES ENUM_STATUS (ID)
				ON DELETE CASCADE,
	CONSTRAINT FK_LANGUAGE_ID 
		FOREIGN KEY (LANGUAGE_ID)
			REFERENCES ENUM_LANGUAGE (ID)
);

INSERT INTO ENUM_EVENT_TYPE(ID,ORDER_CODE,SHORT_NAME,FULL_NAME,STATE_ID)
VALUES
	(1,'001',N'Бемор текшируви',N'Бемор текшируви',1),
	(2,'002',N'Иш юзасидан вазифа',N'Иш юзасидан вазифа',1),
	(3,'003',N'Шахсий иш',N'Шахсий иш',1);

------------------------------------------------------------------------------
CREATE TABLE HL_DOCTOR_CALENDAR
(
	ID 				BIGSERIAL NOT NULL PRIMARY KEY,
	ORGANIZATION_ID INTEGER NOT NULL,	
    EMPLOYEE_ID     INTEGER NOT NULl,

	STATE_ID		INTEGER NOT NULL,

	CREATED_AT		TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY		INT,
	MODIFIED_AT		TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_AT		INT,

    CONSTRAINT FK_ORGANIZATION_ID
        FOREIGN KEY (ORGANIZATION_ID)
            REFERENCES INFO_ORGANIZATION (ID),	
    CONSTRAINT FK_STATE_ID  
		FOREIGN KEY ( STATE_ID )
			REFERENCES ENUM_STATE ( ID )
);

CREATE UNIQUE INDEX UIX_INFO_DOCTOR_CALENDAR
	ON INFO_DOCTOR_CALENDAR(ORGANIZATION_ID, EMPLOYEE_ID);


--INFO_DOCTOR_CALENDAR ning table qismi
CREATE TABLE HL_DOCTOR_CALENDAR_EVENT 
(
	ID 						BIGSERIAL NOT NULL PRIMARY KEY,
	OWNER_ID				INTEGER NOT NULL,

	EVENT_TYPE_ID	    	INTEGER NOT NULL, -- Bemor ko'rigi, Ishga taluqli boshqa event , Shaxsiy event
    EVENT_PRIORITY_ID   	INTEGER NOT NULL,
	MEDICAL_SERVICE_TYPE_ID INTEGER NOT NULL,
    
	PATIENT_NAME			 VARCHAR(500),  --Bemor FISH
	PATIENT_PHONE			 VARCHAR(20),--Bemor Telefon nomeri
		 
	FROM_TIME				 TIME NOT NULL, --soat ... dan boshlanadi
	EVENT_DURATION			 INT, --necha MINUT davom etadi ,Bu ixtiyoriy polya agar TO_TIME tanlansa avtomat tushadi agar,agar bu tanlansa TO_TIME avtomat tushadi
	TO_TIME					 TIME NOT NULL, --soat ... da yakunlanadi
		 
	MESSAGE					 TEXT,
		 
	CREATED_AT		    	 TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY		    	 INT,
	MODIFIED_AT		    	 TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_AT		    	 INT,	
	

    CONSTRAINT FK_OWNER_ID
        FOREIGN KEY (OWNER_ID)
            REFERENCES INFO_DOCTOR_CALENDAR (ID),
    CONSTRAINT FK_EVENT_TYPE_ID 
		FOREIGN KEY ( EVENT_TYPE_ID )
			REFERENCES ENUM_EVENT_TYPE ( ID ),
    CONSTRAINT FK_EVENT_PRIORITY_ID
		FOREIGN KEY ( EVENT_PRIORITY_ID )
			REFERENCES ENUM_EVENT_PRIORITY ( ID ),
	CONSTRAINT FK_MEDICAL_SERVICE_TYPE_Id
		FOREIGN KEY (MEDICAL_SERVICE_TYPE_ID)
			REFERENCES INFO_MEDICAL_SERVICE_TYPE (ID)
);

CREATE UNIQUE INDEX UIX_HL__DOCTOR_CALENDAR_EVENT
	ON HL_DOCTOR_CALENDAR_EVENT(OWNER_ID,FROM_TIME);