CREATE TABLE INFO_REGION
(
 ID 	    		SERIAL NOT NULL primary key,
 ORDER_CODE 		VARCHAR(50),
 CODE	        	VARCHAR(50),
 SOATO	        	VARCHAR(50),
 ROAMING_CODE 		VARCHAR(50),
 SHORT_NAME	 		VARCHAR(250) NOT NULL,
 FULL_NAME	  		VARCHAR(250) NOT NULL,
 COUNTRY_ID 		INT NOT NULL,
 STATE_ID   		INT NOT NULL,
	
 CREATED_AT    		TIMESTAMP WITHOUT TIME ZONE 
							DEFAULT NOW() NOT NULL,
 CREATED_BY		    INT NULL,
 MODIFIED_AT   		TIMESTAMP WITHOUT TIME ZONE,
 MODIFIED_BY   		INT,
 
 CONSTRAINT fk_country_id 
		FOREIGN KEY ( COUNTRY_ID )
			REFERENCES INFO_COUNTRY ( ID ),
 CONSTRAINT fk_state_id
		FOREIGN KEY ( STATE_ID )
			REFERENCES ENUM_STATE ( id )
);
CREATE UNIQUE INDEX info_region_uniques_index_code 
		ON INFO_REGION (CODE)
			WHERE CODE IS NOT NULL;

CREATE UNIQUE INDEX info_region_unique_index_soato
		ON INFO_REGION (SOATO)
			WHERE SOATO IS NOT NULL;
  
CREATE UNIQUE INDEX info_region_unique_index_roaming_code 
		ON INFO_REGION (ROAMING_CODE)
			WHERE ROAMING_CODE IS NOT NULL;