CREATE TABLE INFO_DISTRICT
(
 ID	        		SERIAL NOT NULL PRIMARY KEY,
 ORDER_CODE 		VARCHAR(50), 
 CODE 				VARCHAR(50), 
 SOATO  			VARCHAR(50),
 ROAMING_CODE 		VARCHAR(50),
 SHORT_NAME  		VARCHAR(250) NOT NULL,
 FULL_NAME  		VARCHAR(250) NOT NULL,
 REGION_ID  		INT NOT NULL,
	
 STATE_ID   		INT NOT NULL,	
 CREATED_AT    		TIMESTAMP WITHOUT TIME ZONE 
							DEFAULT NOW() NOT NULL,
 CREATED_BY		    INT NULL,
 MODIFIED_AT   		TIMESTAMP WITHOUT TIME ZONE,
 MODIFIED_BY   		INT,
	
 CONSTRAINT fk_region_id 
	FOREIGN KEY ( REGION_ID ) 
		REFERENCES INFO_REGION ( ID ),
 CONSTRAINT fk_state_id 
	FOREIGN KEY ( STATE_ID )
		REFERENCES ENUM_STATE ( ID )
);

CREATE UNIQUE INDEX info_district_unique_index_code 
	ON INFO_DISTRICT (CODE)
		WHERE CODE IS NOT NULL;

CREATE UNIQUE INDEX info_district_unique_index_soato
	ON INFO_DISTRICT (SOATO)
		WHERE SOATO IS NOT NULL;

CREATE UNIQUE INDEX info_district_unique_index_roaming_code
	ON INFO_DISTRICT (ROAMING_CODE)
		WHERE ROAMING_CODE IS NOT NULL;