CREATE TABLE INFO_DISTRICT_TRANSLATE(
  ID                SERIAL NOT NULL PRIMARY KEY,
  OWNER_ID          INT NOT NULL,
  LANGUAGE_ID       INT NOT NULL,
  COLUMN_NAME       VARCHAR(100) NOT NULL,
  TRANSLATE_TEXT    TEXT NOT NULL,	
	
  CREATED_AT    	TIMESTAMP WITHOUT TIME ZONE 
						DEFAULT NOW() NOT NULL,
  CREATED_BY		INT NULL,
  MODIFIED_AT   	TIMESTAMP WITHOUT TIME ZONE,
  MODIFIED_BY   	INT,
	
  CONSTRAINT fk_owner_id FOREIGN KEY (OWNER_ID) REFERENCES INFO_DISTRICT(ID) ON DELETE CASCADE,
  CONSTRAINT fk_language_id FOREIGN KEY (LANGUAGE_ID) REFERENCES ENUM_LANGUAGE(ID)
);