CREATE TABLE ENUM_GENDER
(
	ID 			INT NOT NULL PRIMARY KEY,
	ORDER_CODE 	VARCHAR(50),
	SHORT_NAME 	VARCHAR(250) NOT NULL,
	FULL_NAME 	VARCHAR(500) NOT NULL,	
	CREATED_AT  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);