INSERT INTO ENUM_DOCUMENT_TYPE (ID, ORDER_CODE, SHORT_NAME, FULL_NAME, STATE_ID) VALUES (1,'1','Паспорт','Паспорт',1);
INSERT INTO ENUM_DOCUMENT_TYPE (ID, ORDER_CODE, SHORT_NAME, FULL_NAME, STATE_ID) VALUES (2,'2','ID карта','ID карта',1);
INSERT INTO ENUM_DOCUMENT_TYPE (ID, ORDER_CODE, SHORT_NAME, FULL_NAME, STATE_ID) VALUES (3,'3','Tug`ilganlik haqida guvohnoma','Tug`ilganlik haqida guvohnoma',1);
INSERT INTO ENUM_DOCUMENT_TYPE (ID, ORDER_CODE, SHORT_NAME, FULL_NAME, STATE_ID) VALUES (4,'4','Chet el hujjati','Chet el hujjati',1);