insert into ENUM_DOCUMENT_TYPE_TRANSLATE(OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (1,1,'full_name',N'Паспорт');
insert into ENUM_DOCUMENT_TYPE_TRANSLATE(OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (2,1,'full_name',N'ID карта');
insert into ENUM_DOCUMENT_TYPE_TRANSLATE(OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (3,1,'full_name',N'Свидетельство о рождении');
insert into ENUM_DOCUMENT_TYPE_TRANSLATE(OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (4,1,'full_name',N'Иностранный документ');
insert into ENUM_DOCUMENT_TYPE_TRANSLATE(OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (1,2,'full_name',N'Паспорт');
insert into ENUM_DOCUMENT_TYPE_TRANSLATE(OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (2,2,'full_name',N'ID карта');
insert into ENUM_DOCUMENT_TYPE_TRANSLATE(OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (3,2,'full_name',N'Туғилганлик тўғрисида гувоҳнома');
insert into ENUM_DOCUMENT_TYPE_TRANSLATE(OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (4,2,'full_name',N'Чет эл ҳужжати');
insert into ENUM_DOCUMENT_TYPE_TRANSLATE(OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (1,3,'full_name',N'Pasport');
insert into ENUM_DOCUMENT_TYPE_TRANSLATE(OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (2,3,'full_name',N'ID karta');
insert into ENUM_DOCUMENT_TYPE_TRANSLATE(OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (3,3,'full_name',N'Tugʼilganlik toʼgʼrisida guvohnoma');
insert into ENUM_DOCUMENT_TYPE_TRANSLATE(OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (4,3,'full_name',N'Chet el hujjati');

insert into ENUM_DOCUMENT_TYPE_TRANSLATE(OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (1,1,'short_name',N'Паспорт');
insert into ENUM_DOCUMENT_TYPE_TRANSLATE(OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (2,1,'short_name',N'ID карта');
insert into ENUM_DOCUMENT_TYPE_TRANSLATE(OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (3,1,'short_name',N'Свидетельство о рождении');
insert into ENUM_DOCUMENT_TYPE_TRANSLATE(OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (4,1,'short_name',N'Иностранный документ');
insert into ENUM_DOCUMENT_TYPE_TRANSLATE(OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (1,2,'short_name',N'Паспорт');
insert into ENUM_DOCUMENT_TYPE_TRANSLATE(OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (2,2,'short_name',N'ID карта');
insert into ENUM_DOCUMENT_TYPE_TRANSLATE(OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (3,2,'short_name',N'Туғилганлик тўғрисида гувоҳнома');
insert into ENUM_DOCUMENT_TYPE_TRANSLATE(OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (4,2,'short_name',N'Чет эл ҳужжати');
insert into ENUM_DOCUMENT_TYPE_TRANSLATE(OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (1,3,'short_name',N'Pasport');
insert into ENUM_DOCUMENT_TYPE_TRANSLATE(OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (2,3,'short_name',N'ID karta');
insert into ENUM_DOCUMENT_TYPE_TRANSLATE(OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (3,3,'short_name',N'Tugʼilganlik toʼgʼrisida guvohnoma');
insert into ENUM_DOCUMENT_TYPE_TRANSLATE(OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (4,3,'short_name',N'Chet el hujjati');
