CREATE TABLE SYS_USER
(
	ID					SERIAL NOT NULL PRIMARY KEY,
	USER_NAME			VARCHAR(250) NOT NULL,
	PASSWORD_HASH		VARCHAR(250) NOT NULL,
	PASSWORD_SALT		VARCHAR(259) NOT NULL,
	EMAIL 				VARCHAR(259),
	PHONE_NUMBER		VARCHAR(50),
	ORGANIZATION_ID		INT NOT NULL,
	PERSON_ID			INT NOT NULL,
	LANGUAGE_ID			INT,
	LAST_ACCESS_TIME	TIMESTAMP WITHOUT TIME ZONE,
	
	STATE_ID			INT NOT NULL,
	CREATED_AT			TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY			INT,
	MODIFIED_AT			TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY			INT,
	
	CONSTRAINT FK_ORGANIZATION_ID
		FOREIGN KEY (ORGANIZATION_ID) 
			REFERENCES INFO_ORGANIZATION (ID),
	CONSTRAINT FK_PERSON_ID
		FOREIGN KEY (PERSON_ID)
			REFERENCES HL_PERSON (ID),
	CONSTRAINT FK_LANGUAGE_ID
		FOREIGN KEY (LANGUAGE_ID)
			REFERENCES ENUM_LANGUAGE (ID),
	CONSTRAINT FK_STATE_ID
		FOREIGN KEY (STATE_ID)
			REFERENCES ENUM_STATE (ID)	
);

CREATE INDEX SYS_USER_INDEX_ORGANIZATION_ID__STATE_ID
	ON SYS_USER (ORGANIZATION_ID , STATE_ID);

CREATE UNIQUE INDEX SYS_USER_INDEX_USER_NAME
	ON SYS_USER(USER_NAME);
	
CREATE UNIQUE INDEX SYS_USER_INDEX_EMAIL
	ON SYS_USER (EMAIL)
		WHERE EMAIL IS NOT NULL;