CREATE TABLE SYS_ROLE
(
	ID				SERIAL NOT NULL PRIMARY KEY,
	ORDER_CODE		VARCHAR(20),
	SHORT_NAME		VARCHAR(250) NOT NULL,
	FULL_NAME		VARCHAR(500) NOT NULL,
	IS_ADMIN		BOOLEAN NOT NULL,
	IS_DEFAULT		BOOLEAN NOT NULL,
	
	STATE_ID		INT NOT NULL,
	CREATED_AT		TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY		INT,
	MODIFIED_AT		TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY		INT,
	
	CONSTRAINT FK_STATE_ID
		FOREIGN KEY (STATE_ID)
			REFERENCES ENUM_STATE (ID)
);