CREATE TABLE SYS_USER_LOG (
	ID				SERIAL NOT NULL PRIMARY KEY,
	ACTION_NAME     VARCHAR(200) NOT NULL,
	USER_NAME       VARCHAR(250) NOT NULL,
	USER_ID         INT NULL,
	IP_ADDRESS      VARCHAR(200),
	USER_AGENT		VARCHAR(2000),
	CREATED_AT      TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL
);