
CREATE TABLE HL_EMPLOYEE
(
    ID                      SERIAL NOT NULL PRIMARY KEY,
    PARENT_ORGANIZATION_ID  INT,
    ORGANIZATION_ID         INT NOT NULL,
    PHONE_NUMBER		    VARCHAR(50),
    POSITION_ID             INT NOT NULL,
    PERSON_ID               INT NOT NULL,
    USER_ID                 INT,
	SUBJECT_ID              INT,

	STATE_ID			    INT NOT NULL,
	CREATED_AT			    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY			    INT,
	MODIFIED_AT			    TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY			    INT,

    CONSTRAINT FK_PERSON_ID                 FOREIGN KEY ( PERSON_ID )               REFERENCES HL_PERSON ( ID ),
    CONSTRAINT FK_STATE_ID                  FOREIGN KEY ( STATE_ID )                REFERENCES ENUM_STATE ( ID ),
    CONSTRAINT FK_PARENT_ORGANIZATION_ID    FOREIGN KEY ( PARENT_ORGANIZATION_ID )  REFERENCES INFO_ORGANIZATION ( ID ),
    CONSTRAINT FK_ORGANIZATION_ID           FOREIGN KEY ( ORGANIZATION_ID )         REFERENCES INFO_ORGANIZATION ( ID ),
    CONSTRAINT FK_USER_ID                   FOREIGN KEY ( USER_ID )                 REFERENCES SYS_USER ( ID ),
    CONSTRAINT FK_POSITION_ID               FOREIGN KEY ( POSITION_ID )             REFERENCES HL_POSITION ( ID )
);

CREATE INDEX IX_HL_EMPLOYEE__STATE_ID__ORGANIZATION_ID
	ON HL_EMPLOYEE(STATE_ID,ORGANIZATION_ID);
	
CREATE UNIQUE INDEX UIX_HL_EMPLOYEE__USER_ID 
	ON HL_EMPLOYEE(USER_ID)
	WHERE USER_ID IS NOT NULL;