CREATE TABLE HL_STUDENT
(
	ID						INT NOT NULL PRIMARY KEY,
	PERSON_ID				INT NOT NULL,
	ORGANIZATION_ID			INT NOT NULL,
	TEACHER_EMPLOYEEMENT_ID	INT NOT NULL,
	SUBJECT_ID				INT NOT NULL,
	PHONE_NUMBER			VARCHAR(50),
	PARENT_ID    			INT,
	PARENT_PHONE_NUMBER		VARCHAR(50),

	STATE_ID			    INT NOT NULL,
	CREATED_AT			    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY			    INT,
	MODIFIED_AT			    TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY			    INT,
	
	CONSTRAINT FK_PERSON_ID                 
		FOREIGN KEY ( PERSON_ID ) 
			REFERENCES HL_PERSON ( ID ),
	CONSTRAINT FK_PARENT_ID                 
		FOREIGN KEY ( PARENT_ID ) 
			REFERENCES HL_PERSON ( ID ),
    CONSTRAINT FK_ORGANIZATION_ID   
		FOREIGN KEY ( ORGANIZATION_ID )
			REFERENCES INFO_ORGANIZATION ( ID ),
    CONSTRAINT FK_TEACHER_EMPLOYEEMENT_ID
		FOREIGN KEY ( TEACHER_EMPLOYEEMENT_ID )              
			REFERENCES HL_EMPLOYEE ( ID ),
    CONSTRAINT FK_SUBJECT_ID 
		FOREIGN KEY ( SUBJECT_ID )     
			REFERENCES HL_SUBJECT ( ID ),
    CONSTRAINT FK_STATE_ID   
		FOREIGN KEY ( STATE_ID )     
			REFERENCES ENUM_STATE ( ID )
);