CREATE TABLE ENUM_LANGUAGE
(
	ID 			INT NOT NULL PRIMARY KEY,
	CODE 		VARCHAR(10) NOT NULL,
	SHORT_NAME 	VARCHAR(50) NOT NULL,
	FULL_NAME 	VARCHAR(100) NOT NULL,
	CREATED_AT	TIMESTAMP WITHOUT TIME ZONE 
						DEFAULT NOW() NOT NULL
);