CREATE TABLE INFO_ORGANIZATION
(
	ID					serial NOT NULL PRIMARY KEY,
	ORDER_CODE			VARCHAR(50),
	SHORT_NAME			VARCHAR(250) NOT NULL,
	FULL_NAME			VARCHAR(300) NOT NULL,
	INN					VARCHAR(9),
	PARENT_ID			INT,
	COUNTRY_ID			INT NOT NULL,
	REGION_ID			INT NOT NULL,
	DISTRICT_ID			INT,
	ADDRESS				VARCHAR(500) NULL,
	PHONE_NUMBER		VARCHAR(250),
	OKED_ID				INT,
	DIRECTOR			VARCHAR(250) NULL,
	VAT_CODE			VARCHAR(12) NULL,
	ZIP_CODE			VARCHAR(50) NULL,
	LATITUDE			VARCHAR(50),
	LONGITUDE			VARCHAR(50),

 	STATE_ID   			INT NOT NULL,	
 	CREATED_AT    		TIMESTAMP WITHOUT TIME ZONE 
							DEFAULT NOW() NOT NULL,
 	CREATED_BY		    INT NULL,
 	MODIFIED_AT   		TIMESTAMP WITHOUT TIME ZONE,
 	MODIFIED_BY   		INT,
 
	CONSTRAINT fk_country_id FOREIGN KEY ( country_id ) REFERENCES info_country ( ID ),
	--CONSTRAINT fk_oked_id FOREIGN KEY ( oked_id ) REFERENCES info_oked ( ID ),
	CONSTRAINT fk_region_id FOREIGN KEY ( region_id ) REFERENCES info_region ( ID ),
	CONSTRAINT fk_district_id FOREIGN KEY ( district_id ) REFERENCES info_district ( ID ),
	CONSTRAINT fk_state_id FOREIGN KEY ( state_id ) REFERENCES enum_state ( ID ),
	CONSTRAINT fk_parent_id FOREIGN KEY ( parent_id ) REFERENCES INFO_ORGANIZATION ( ID )
);

CREATE UNIQUE INDEX info_organization_unique_index_inn 
	ON INFO_ORGANIZATION (INN);