CREATE TABLE INFO_CITIZENSHIP
(
	ID				SERIAL NOT NULL PRIMARY KEY,
	WB_CODE			VARCHAR(50),
	SHORT_NAME		VARCHAR(250) NOT NULL,
	FULL_NAME		VARCHAR(250) NOT NULL,
	
	STATE_ID		INT NOT NULL,
	CREATED_AT		TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY		INT,
	MODIFIED_AT		TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY		INT,
	
	CONSTRAINT FK_STATE_ID
		FOREIGN KEY (STATE_ID)
			REFERENCES ENUM_STATE (ID)	
);

CREATE UNIQUE INDEX INFO_CITIZENSHIP_UNIQUE_INDEX_WB_CODE 
	ON INFO_NATIONALITY (WB_CODE)
		WHERE WB_CODE IS NOT NULL;