INSERT INTO HL_PERSON (ID,DOCUMENT_TYPE_ID,DOCUMENT_SERIA,DOCUMENT_NUMBER,BIRTH_ON,LAST_NAME,FIRST_NAME,GENDER_ID,STATE_ID)
values (1,1,N'AA', N'0000000',now(), N'Administrator', N'Administrator', 1, 1);
