CREATE TABLE SYS_MODULE_SUB_GROUP
(
 ID         		SERIAL NOT NULL PRIMARY KEY,
 CODE       		VARCHAR(100) NOT NULL,
 SHORT_NAME 		VARCHAR(250) NOT NULL,
 FULL_NAME  		VARCHAR(300) NOT NULL,
 GROUP_ID   		INT NOT NULL,
	
 CREATED_AT			TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
 CREATED_BY			INT,
 MODIFIED_AT		TIMESTAMP WITHOUT TIME ZONE,
 MODIFIED_BY		INT,
 
 CONSTRAINT FK_GROUP_ID FOREIGN KEY (GROUP_ID) REFERENCES SYS_MODULE_GROUP(ID)
);

CREATE UNIQUE INDEX SYS_MODULE_SUB_GROUP_UNIQUE_INDEX_CODE ON SYS_MODULE_SUB_GROUP (CODE);