CREATE TABLE SYS_ROLE_MODULE (
    ID 			SERIAL NOT NULL PRIMARY KEY,
    ROLE_ID 	INT NOT NULL,
    MODULE_ID 	INT NOT NULL,
    CREATED_BY  INT NOT NULL,
    MODIFIED_BY INT,
    CREATED_AT  TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,

    CONSTRAINT FK_ROLE_ID 
		FOREIGN KEY (ROLE_ID)
			REFERENCES SYS_ROLE(ID) ON DELETE CASCADE,
    CONSTRAINT FK_MODULE_ID 
		FOREIGN KEY (MODULE_ID)
			REFERENCES SYS_MODULE(ID),
    CONSTRAINT FK_CREATED_BY
		FOREIGN KEY (CREATED_BY)
			REFERENCES SYS_USER(ID)
);
