CREATE TABLE HL_EMPLOYEE_PHONE_NUMBER
(
    ID              SERIAL NOT NULL PRIMARY KEY,
    OWNER_ID     INT NOT NULL,
    PHONE_NUMBER    VARCHAR(20) NOT NULL,    
	
	STATE_ID		INT NOT NULL,
	CREATED_AT		TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY		INT,
	MODIFIED_AT		TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY		INT,
	
	CONSTRAINT FK_STATE_ID
		FOREIGN KEY (STATE_ID)
			REFERENCES ENUM_STATE (ID),	
	CONSTRAINT FK_OWNER_ID
		FOREIGN KEY (OWNER_ID)
			REFERENCES HL_EMPLOYEE (ID)
);