CREATE TABLE HL_EMPLOYEE_PHONE_NUMBER_SOCIAL_NETWORK
(
    ID                      BIGSERIAL NOT NULL PRIMARY KEY,
    OWNER_ID                INT NOT NULL,
    SOCIAL_NETWORK_TYPE_ID  INT NOT NULL,
    
	
	STATE_ID		INT NOT NULL,
	CREATED_AT		TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY		INT,
	MODIFIED_AT		TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY		INT,
	
	CONSTRAINT FK_STATE_ID
		FOREIGN KEY (STATE_ID)
			REFERENCES ENUM_STATE (ID),	
	CONSTRAINT FK_OWNER_ID
		FOREIGN KEY (OWNER_ID)
			REFERENCES HL_EMPLOYEE_PHONE_NUMBER (ID),
	CONSTRAINT FK_SOCIAL_NETWORK_TYPE_ID
		FOREIGN KEY (SOCIAL_NETWORK_TYPE_ID)
			REFERENCES ENUM_SOCIAL_NETWORK_TYPE (ID)
)