CREATE TABLE HL_DEPARTMENT
(
	ID						SERIAL NOT NULL PRIMARY KEY,

	CODE					VARCHAR(50) NOT NULL,	
	ORDER_CODE				VARCHAR(50),

	SHORT_NAME				VARCHAR(500) NOT NULL,
	FULL_NAME				VARCHAR(500) NOT NULL,
	ORGANIZATION_ID			INT NOT NULL,
	STATE_ID			    INT NOT NULL,
	
	CREATED_AT			    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY			    INT,
	MODIFIED_AT			    TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY			    INT,

	CONSTRAINT FK_STATE_ID			
		FOREIGN KEY ( STATE_ID )	
			REFERENCES ENUM_STATE ( ID ),
	CONSTRAINT FK_ORGANIZATION_ID 
		FOREIGN KEY (ORGANIZATION_ID)
			REFERENCES INFO_ORGANIZATION (ID)
);

CREATE UNIQUE INDEX HL_DEPARTMENT_UNIQUE_INDEX_CODE ON HL_POSITION (CODE);