BEGIN;
INSERT INTO ENUM_PLASTIC_CARD_TYPE (ID, ORDER_CODE, SHORT_NAME, FULL_NAME, STATE_ID) VALUES (1,' 01','Humo','Humo', 1);
INSERT INTO ENUM_PLASTIC_CARD_TYPE (ID, ORDER_CODE, SHORT_NAME, FULL_NAME, STATE_ID) VALUES (2,'02','UzCard','UzCard', 1);
COMMIT;