BEGIN;
insert into ENUM_PLASTIC_CARD_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (1,1,'full_name',N'Хумо');
insert into ENUM_PLASTIC_CARD_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (2,1,'full_name',N'УзКард');
insert into ENUM_PLASTIC_CARD_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (1,2,'full_name',N'Хумо');
insert into ENUM_PLASTIC_CARD_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (2,2,'full_name',N'УзКард');
insert into ENUM_PLASTIC_CARD_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (1,3,'full_name',N'Humo');
insert into ENUM_PLASTIC_CARD_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (2,3,'full_name',N'UzCard');




insert into ENUM_PLASTIC_CARD_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (1,1,'short_name',N'Хумо');
insert into ENUM_PLASTIC_CARD_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (2,1,'short_name',N'УзКард');
insert into ENUM_PLASTIC_CARD_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (1,2,'short_name',N'Хумо');
insert into ENUM_PLASTIC_CARD_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (2,2,'short_name',N'УзКард');
insert into ENUM_PLASTIC_CARD_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (1,3,'short_name',N'Humo');
insert into ENUM_PLASTIC_CARD_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) values (2,3,'short_name',N'UzCard');
COMMIT;