CREATE TABLE HL_EMPLOYEE_PLASTIC_CARD
(
    ID              BIGSERIAL NOT NULL PRIMARY KEY,
    OWNER_ID        INT NOT NULL,
    BANK_ID         INT NOT NULL,
    CODE            VARCHAR(30) NOT NULL,
    DETAILS         TEXT,    

	CREATED_AT	    TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY	    INT,
	MODIFIED_AT	    TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY	    INT,

    CONSTRAINT FK_OWNER_ID
        FOREIGN KEY (OWNER_ID)
            REFERENCES HL_EMPLOYEE (ID),
    CONSTRAINT FK_BANK_ID
        FOREIGN KEY (BANK_ID)
            REFERENCES INFO_BANK (ID)
    
)