BEGIN;
 INSERT INTO ENUM_APPOINT_ORDER_TYPE (ID, ORDER_CODE, SHORT_NAME, FULL_NAME, STATE_ID) VALUES (1,'001', N'Прием на работу', N'Прием на работу', 1);
INSERT INTO ENUM_APPOINT_ORDER_TYPE (ID, ORDER_CODE, SHORT_NAME, FULL_NAME, STATE_ID) VALUES (2,'002', N'Перевод на другую должность', N'Перевод на другую должность', 1);
INSERT INTO ENUM_APPOINT_ORDER_TYPE (ID, ORDER_CODE, SHORT_NAME, FULL_NAME, STATE_ID) VALUES (3,'003', N'Увольнение', N'Увольнение', 1);
INSERT INTO ENUM_APPOINT_ORDER_TYPE (ID, ORDER_CODE, SHORT_NAME, FULL_NAME, STATE_ID) VALUES (4,'004', N'Совмещение должностей', N'Совмещение должностей', 1);
COMMIT;