BEGIN;
INSERT INTO ENUM_APPOINT_ORDER_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) VALUES (1,1,'full_name',N'Прием на работу');
INSERT INTO ENUM_APPOINT_ORDER_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) VALUES (2,1,'full_name',N'Перевод на другую должность');
INSERT INTO ENUM_APPOINT_ORDER_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) VALUES (3,1,'full_name',N'Увольнение');
INSERT INTO ENUM_APPOINT_ORDER_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) VALUES (4,1,'full_name',N'Совмещение должностей');
INSERT INTO ENUM_APPOINT_ORDER_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) VALUES (1,2,'full_name',N'Ишга қабул қилиш');
INSERT INTO ENUM_APPOINT_ORDER_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) VALUES (2,2,'full_name',N'Бошқа лавозимга ўтказиш');
INSERT INTO ENUM_APPOINT_ORDER_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) VALUES (3,2,'full_name',N'Ишдан бўшатиш');
INSERT INTO ENUM_APPOINT_ORDER_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) VALUES (4,2,'full_name',N'Бир нечта касб ва лавозимда ишлаш');
INSERT INTO ENUM_APPOINT_ORDER_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) VALUES (1,3,'full_name',N'Ishga qabul qilish');
INSERT INTO ENUM_APPOINT_ORDER_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) VALUES (2,3,'full_name',N'Boshqa lavozimga o‘tkazish');
INSERT INTO ENUM_APPOINT_ORDER_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) VALUES (3,3,'full_name',N'Ishdan bo‘shatish');
INSERT INTO ENUM_APPOINT_ORDER_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) VALUES (4,3,'full_name',N'Bir nechta kasb va lavozimda ishlash');

INSERT INTO ENUM_APPOINT_ORDER_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) VALUES (1,1,'short_name',N'Прием на работу');
INSERT INTO ENUM_APPOINT_ORDER_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) VALUES (2,1,'short_name',N'Перевод на другую должность');
INSERT INTO ENUM_APPOINT_ORDER_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) VALUES (3,1,'short_name',N'Увольнение');
INSERT INTO ENUM_APPOINT_ORDER_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) VALUES (4,1,'short_name',N'Совмещение должностей');
INSERT INTO ENUM_APPOINT_ORDER_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) VALUES (1,2,'short_name',N'Ишга қабул қилиш');
INSERT INTO ENUM_APPOINT_ORDER_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) VALUES (2,2,'short_name',N'Бошқа лавозимга ўтказиш');
INSERT INTO ENUM_APPOINT_ORDER_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) VALUES (3,2,'short_name',N'Ишдан бўшатиш');
INSERT INTO ENUM_APPOINT_ORDER_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) VALUES (4,2,'short_name',N'Бир нечта касб ва лавозимда ишлаш');
INSERT INTO ENUM_APPOINT_ORDER_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) VALUES (1,3,'short_name',N'Ishga qabul qilish');
INSERT INTO ENUM_APPOINT_ORDER_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) VALUES (2,3,'short_name',N'Boshqa lavozimga o‘tkazish');
INSERT INTO ENUM_APPOINT_ORDER_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) VALUES (3,3,'short_name',N'Ishdan bo‘shatish');
INSERT INTO ENUM_APPOINT_ORDER_TYPE_TRANSLATE (OWNER_ID, LANGUAGE_ID, COLUMN_NAME, TRANSLATE_TEXT) VALUES (4,3,'short_name',N'Bir nechta kasb va lavozimda ishlash');

COMMIT;