CREATE TABLE DOC_APPOINT_EMPLOYEE
(
	ID				BIGSERIAL NOT NULL PRIMARY KEY,
	
	DOC_NUMBER		VARCHAR(250) NOT NULL,
	DOC_ON			DATE NOT NULL,
	
	TABLE_ID		INT NOT NULL,
	STATUS_ID		INT NOT NULL,
	
	CREATED_AT		TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY		INT,
	MODIFIED_AT		TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY		INT,
	
	CONSTRAINT FK_TABLE_ID
		FOREIGN KEY (TABLE_ID)
			REFERENCES SYS_TABLE (ID),	
	CONSTRAINT FK_STATUS_ID
		FOREIGN KEY (STATUS_ID)
			REFERENCES ENUM_STATUS (ID)	
);

INSERT INTO SYS_TABLE (ID,SHORT_NAME,FULL_NAME,DB_TABLE_NAME)
	VALUES (2,N'Ходимни тайинлаш',N'Ходимни тайинлаш',N'DOC_APPOINT_EMPLOYEE');