CREATE SEQUENCE SEQ_EMPLOYEE_MANAGE;

CREATE TABLE DOC_APPOINT_EMPLOYEE_TABLE
(
    ID                                  BIGSERIAL NOT NULL PRIMARY KEY,
    
    OWNER_ID                            BIGINT NOT NULL,

    START_ON                            DATE NOT NULL,
    END_ON                              DATE,

    APPOINT_ORDER_TYPE_ID               INT NOT NULL,
    DETAILS                             VARCHAR(600),
    EMPLOYEE_RATE                       NUMERIC(18, 2) NOT NULL, --ishchining stavkasi

    DEPARTMENT_ID                       INT,
    POSITION_ID                         INT,
    EMPLOYEE_ID                         INT NOT NULL,

    --EMPLOYMENT_TYPE_ID                  INT,
    --WORK_SCHEDULE_ID                    INT,
    EMPLOYEE_MANAGE_ID                  INT DEFAULT NEXTVAL('SEQ_EMPLOYEE_MANAGE') UNIQUE,

    FROM_DEPARTMENT_ID                  INT,
    FROM_POSITION_ID                    INT,
    FROM_EMPLOYEE_MANAGE_ID             INT,
    FROM_EMPLOYEE_RATE                  NUMERIC(18, 2),

    CONSTRAINT FK__OWNER FOREIGN KEY (OWNER_ID) 
    REFERENCES DOC_APPOINT_EMPLOYEE (ID),

    CONSTRAINT FK__DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) 
    REFERENCES HL_DEPARTMENT (ID),

    CONSTRAINT FK__FROM_DEPARTMENT FOREIGN KEY (FROM_DEPARTMENT_ID) 
    REFERENCES HL_DEPARTMENT (ID),

    CONSTRAINT FK__EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) 
    REFERENCES HL_EMPLOYEE (ID),

    CONSTRAINT FK__POSITION FOREIGN KEY (POSITION_ID) 
    REFERENCES HL_POSITION (ID),

    CONSTRAINT FK__FROM_POSITION FOREIGN KEY (FROM_POSITION_ID) 
    REFERENCES HL_POSITION (ID),

    --CONSTRAINT FK__WORK_SCHEDULE FOREIGN KEY (WORK_SCHEDULE_ID) 
    --REFERENCES INFO_WORK_SCHEDULE (ID),

    --CONSTRAINT FK__EMPLOYEMENT_TYPE FOREIGN KEY (EMPLOYMENT_TYPE_ID) 
    --REFERENCES ENUM_EMPLOYMENT_TYPE (ID),

    CONSTRAINT FK__APPOINT_ORDER_TYPE FOREIGN KEY (APPOINT_ORDER_TYPE_ID) 
    REFERENCES ENUM_APPOINT_ORDER_TYPE (ID)
);


INSERT INTO SYS_TABLE (ID,SHORT_NAME,FULL_NAME,DB_TABLE_NAME)
	VALUES (3,N'Ходимни тайинлаш (Таблица)',N'Ходимни тайинлаш (Таблица)',N'DOC_APPOINT_EMPLOYEE_TABLE');