CREATE TABLE HL_MEDICAL_SERVICE_PRICE
(
	ID			 			BIGSERIAL NOT NULL PRIMARY KEY,
	ORGANIZATION_ID			INT NOT NULL,
	MEDICAL_SERVICE_TYPE_ID	INT NOT NULL,
	PRICE					NUMERIC(18,2),
	EMPLOYEE_ID				INT,
	
	STATE_ID				INT NOT NULL,
			
	CREATED_AT				TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY				INT,
	MODIFIED_AT				TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_BY				INT,
	
	CONSTRAINT FK_STATE_ID
		FOREIGN KEY (STATE_ID)
			REFERENCES ENUM_STATE (ID),	
	CONSTRAINT FK_ORGANIZATION_ID
		FOREIGN KEY (ORGANIZATION_ID)
			REFERENCES INFO_ORGANIZATION (ID),	
	CONSTRAINT FK_MEDICAL_SERVICE_TYPE_ID
		FOREIGN KEY (MEDICAL_SERVICE_TYPE_ID)
			REFERENCES INFO_MEDICAL_SERVICE_TYPE (ID),	
	CONSTRAINT FK_EMPLOYEE_ID
		FOREIGN KEY (EMPLOYEE_ID)
			REFERENCES HL_EMPLOYEE (ID)		
);

CREATE UNIQUE INDEX UIX_HL_MEDICAL_SERVICE_PRICE
	ON HL_MEDICAL_SERVICE_PRICE(ORGANIZATION_ID,EMPLOYEE_ID,MEDICAL_SERVICE_TYPE_ID,STATE_ID);