CREATE TABLE  ENUM_EVENT_PRIORITY  --Success,Primary,Info,Danger,Dark...
(
	ID 				SERIAL NOT NULL,
	ORDER_CODE		VARCHAR(50),

	SHORT_NAME		VARCHAR(20) NOT NULL,
	FULL_NAME		VARCHAR(20) NOT NULL,
	
	STATE_ID		INT NOT NULL,	
	CREATED_AT		TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	
	CONSTRAINT FK_STATE_ID
		FOREIGN KEY (STATE_ID)
			REFERENCES ENUM_STATE (ID)
);