CREATE TABLE ENUM_EVENT_TYPE 	-- Bemor ko'rigi, Ishga taluqli boshqa event , Shaxsiy event
(
    ID 				INT NOT NULL PRIMARY KEY,
    ORDER_CODE 		VARCHAR(50),
    SHORT_NAME 		VARCHAR(250) not null,
    FULL_NAME  		VARCHAR(300) not null,
	STATE_ID		INT NOT NULL,
	
    CREATED_AT 		TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
	
	CONSTRAINT FK_STATE_ID
		FOREIGN KEY (STATE_ID)
			REFERENCES ENUM_STATE (ID)
);