CREATE TABLE HL_DOCTOR_CALENDAR
(
	ID 				BIGSERIAL NOT NULL PRIMARY KEY,
	ORGANIZATION_ID INTEGER NOT NULL,	
    EMPLOYEE_ID     INTEGER NOT NULl,

	STATE_ID		INTEGER NOT NULL,

	CREATED_AT		TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY		INT,
	MODIFIED_AT		TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_AT		INT,

    CONSTRAINT FK_ORGANIZATION_ID
        FOREIGN KEY (ORGANIZATION_ID)
            REFERENCES INFO_ORGANIZATION (ID),	
    CONSTRAINT FK_STATE_ID  
		FOREIGN KEY ( STATE_ID )
			REFERENCES ENUM_STATE ( ID )
);

CREATE UNIQUE INDEX UIX_INFO_DOCTOR_CALENDAR__ORGANIZATION_ID__EMPLOYEE_ID
	ON HL_DOCTOR_CALENDAR(ORGANIZATION_ID, EMPLOYEE_ID);