CREATE TABLE HL_DOCTOR_CALENDAR_EVENT 
(
	ID 						BIGSERIAL NOT NULL PRIMARY KEY,
	OWNER_ID				INTEGER NOT NULL,

	EVENT_TYPE_ID	    	INTEGER NOT NULL, -- Bemor ko'rigi, Ishga taluqli boshqa event , Shaxsiy event
    EVENT_PRIORITY_ID   	INTEGER NOT NULL,
	MEDICAL_SERVICE_TYPE_ID INTEGER NOT NULL,
    
	PATIENT_NAME			 VARCHAR(500),  --Bemor FISH
	PATIENT_PHONE			 VARCHAR(20),--Bemor Telefon nomeri
		 
	FROM_TIME				 TIME NOT NULL, --soat ... dan boshlanadi
	EVENT_DURATION			 INT, --necha MINUT davom etadi ,Bu ixtiyoriy polya agar TO_TIME tanlansa avtomat tushadi agar,agar bu tanlansa TO_TIME avtomat tushadi
	TO_TIME					 TIME NOT NULL, --soat ... da yakunlanadi
		 
	MESSAGE					 TEXT,
		 
	CREATED_AT		    	 TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
	CREATED_BY		    	 INT,
	MODIFIED_AT		    	 TIMESTAMP WITHOUT TIME ZONE,
	MODIFIED_AT		    	 INT,	
	

    CONSTRAINT FK_OWNER_ID
        FOREIGN KEY (OWNER_ID)
            REFERENCES HL_DOCTOR_CALENDAR (ID),
    CONSTRAINT FK_EVENT_TYPE_ID 
		FOREIGN KEY ( EVENT_TYPE_ID )
			REFERENCES ENUM_EVENT_TYPE ( ID ),
    CONSTRAINT FK_EVENT_PRIORITY_ID
		FOREIGN KEY ( EVENT_PRIORITY_ID )
			REFERENCES ENUM_EVENT_PRIORITY ( ID ),
	CONSTRAINT FK_MEDICAL_SERVICE_TYPE_Id
		FOREIGN KEY (MEDICAL_SERVICE_TYPE_ID)
			REFERENCES INFO_MEDICAL_SERVICE_TYPE (ID)
);

CREATE UNIQUE INDEX UIX_HL_DOCTOR_CALENDAR_EVENT__OWNER_ID__FROM_TIME
	ON HL_DOCTOR_CALENDAR_EVENT(OWNER_ID,FROM_TIME);